<#
  One-click deployment for the Vulhub Hub on Windows (PowerShell).

  Requires Docker Desktop (with WSL2 or Hyper-V backend). If Docker is missing the
  script tries to install it via winget, then asks you to start Docker Desktop.
  If the sibling ..\vulhub catalog is missing it is cloned from GitHub. It then
  writes .env (random SECRET_KEY + random admin password, host IP as
  SERVER_HOST, vulhub mount) and runs: docker compose up -d --build.

  Usage (from the vulhub-hub directory):
    powershell -ExecutionPolicy Bypass -File .\deploy.ps1

  Linux / macOS users: run ./deploy.sh instead.
#>
[CmdletBinding()]
param()
$ErrorActionPreference = 'Stop'

function Log  ($m) { Write-Host "==> $m" -ForegroundColor Green }
function Warn ($m) { Write-Host "[!] $m"  -ForegroundColor Yellow }
function Die  ($m) { Write-Host "[x] $m"  -ForegroundColor Red; exit 1 }

Set-Location -Path $PSScriptRoot

function Wait-ForDocker {
  for ($i = 0; $i -lt 60; $i++) {
    try { docker info *> $null; if ($LASTEXITCODE -eq 0) { return } } catch {}
    Start-Sleep -Seconds 2
  }
  Die "Docker daemon not ready after ~120s; start Docker Desktop and re-run this script."
}

function Ensure-Docker {
  if (Get-Command docker -ErrorAction SilentlyContinue) {
    Log "Docker already present: $(docker --version)"
  }
  elseif (Get-Command winget -ErrorAction SilentlyContinue) {
    Log "Installing Docker Desktop via winget (Docker.DockerDesktop)"
    winget install -e --id Docker.DockerDesktop --accept-package-agreements --accept-source-agreements
    Warn "Docker Desktop installed. Start it (and finish first-run setup), then re-run this script."
    exit 0
  }
  else {
    Die "Docker not found. Install Docker Desktop from https://www.docker.com/products/docker-desktop/, start it, then re-run this script."
  }
  docker info *> $null
  if ($LASTEXITCODE -ne 0) {
    Log "Starting Docker Desktop and waiting for the daemon..."
    $exe = Join-Path $env:ProgramFiles 'Docker\Docker\Docker Desktop.exe'
    if (Test-Path $exe) { Start-Process $exe | Out-Null }
    Wait-ForDocker
  }
  docker compose version *> $null
  if ($LASTEXITCODE -ne 0) { Die "docker compose v2 unavailable; update Docker Desktop to a recent version." }
}

function Ensure-Vulhub {
  # The platform reads its catalog from a sibling ../vulhub directory. On a fresh
  # deployment only vulhub-hub/ is present, so clone the upstream catalog.
  $vulhubDir = Join-Path $PSScriptRoot '..\vulhub'
  if (Test-Path (Join-Path $vulhubDir '.git')) {
    Log "vulhub catalog already present ($vulhubDir)"
    return
  }
  if (Test-Path $vulhubDir) {
    Warn "vulhub directory exists but is not a git clone; leaving it as-is"
    return
  }
  if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    if (Get-Command winget -ErrorAction SilentlyContinue) {
      Log "Installing Git via winget (Git.Git)"
      winget install -e --id Git.Git --accept-package-agreements --accept-source-agreements
    }
    if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
      Die "git not found. Install Git from https://git-scm.com/download/win, then re-run this script."
    }
  }
  Log "Cloning vulhub catalog (git clone https://github.com/vulhub/vulhub.git)"
  git clone https://github.com/vulhub/vulhub.git $vulhubDir
  if ($LASTEXITCODE -ne 0) { Die "git clone failed; check your network and retry." }
}

function New-RandomString {
  param([int]$Length, [string]$Charset)
  $bytes = New-Object 'System.Byte[]' $Length
  [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
  -join ($bytes | ForEach-Object { $Charset[$_ % $Charset.Length] })
}

function Get-HostIPv4 {
  try {
    $ip = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction Stop |
      Where-Object { $_.IPAddress -ne '127.0.0.1' -and $_.PrefixOrigin -ne 'WellKnown' } |
      Select-Object -First 1 -ExpandProperty IPAddress
    if ($ip) { return $ip }
  } catch {}
  return 'localhost'
}

$script:NewAdminPw = ''

function Write-EnvFile {
  if (Test-Path .env) { Log ".env already exists; leaving it unchanged"; return }
  $alnum   = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
  $hex     = '0123456789abcdef'
  $secret  = New-RandomString -Length 64 -Charset $hex
  $adminPw = New-RandomString -Length 16 -Charset $alnum
  $script:NewAdminPw = $adminPw
  $ip = Get-HostIPv4
  $vulhub = Resolve-Path (Join-Path $PSScriptRoot '..\vulhub') -ErrorAction SilentlyContinue
  if (-not $vulhub) { Warn "vulhub not found beside vulhub-hub/; edit .env afterwards" }
  # Docker Desktop accepts forward-slashed Windows paths in compose bind mounts.
  $vulhubPath = if ($vulhub) { $vulhub.Path -replace '\\', '/' } else { '../vulhub' }
  Log "Writing .env (SERVER_HOST=$ip, vulhub=$vulhubPath)"
  $lines = @(
    '# Generated by deploy.ps1. Adjust as needed, then re-run the deploy script.',
    "SECRET_KEY=$secret",
    "SERVER_HOST=$ip",
    'ADMIN_USERNAME=admin',
    "ADMIN_PASSWORD=$adminPw",
    'MAX_INSTANCES_PER_USER=3',
    '# On Windows the container path cannot equal the host path, so vulhub targets',
    '# that use relative bind mounts may fail; port-mapping targets work fine.',
    "VULHUB_HOST_PATH=$vulhubPath",
    'VULHUB_MOUNT=/vulhub'
  )
  Set-Content -Path .env -Value $lines -Encoding ascii
}

function Main {
  Ensure-Docker
  Ensure-Vulhub
  Write-EnvFile
  Log "Building and starting the platform (docker compose up -d --build)"
  docker compose up -d --build
  if ($LASTEXITCODE -ne 0) { Die "docker compose failed; see the output above." }
  $ip = Get-HostIPv4
  Write-Host ''
  Log "Deployment complete."
  Log "URL:   http://$($ip):8000"
  Log "Check: curl http://localhost:8000/api/health"
  if ($script:NewAdminPw) {
    Write-Host ''
    Warn "==================== SAVE THESE CREDENTIALS ===================="
    Warn "Initial admin account (generated once, on a fresh database):"
    Warn "    username: admin"
    Warn "    password: $($script:NewAdminPw)"
    Warn "Stored as ADMIN_PASSWORD in $PSScriptRoot\.env. Change it after login."
    Warn "==============================================================="
  }
  else {
    Log "Existing .env kept; admin password unchanged (see ADMIN_PASSWORD in .env)."
  }
  Warn "If the platform port is blocked, allow it in Windows Firewall (elevated):"
  Warn "  New-NetFirewallRule -DisplayName 'vulhub-hub 8000' -Direction Inbound -LocalPort 8000 -Protocol TCP -Action Allow"
}

Main
